### ISSUE TITLE
where is xinshuo_io?

### ISSUE THREAD

**Issue by zuzi2015** [JYS997760473/Multi-Object-tracking-2D#1]
没有xinshuo_io这个文件

**Comment by JYS997760473** [comment]
I have upload a .zip file named Xinshuo_Pytool-master and you can upzip it and tansfer xinshuo_io and other packages to your python environment's site-packages

**Comment by zuzi2015** [comment]
我放到我了我的虚拟环境中的site-packages,但是还是报错：
ImportError: cannot import name 'load_list_from_folder' from 'xinshuo_io' (unknown location)
@JYS997760473

**Comment by zuzi2015** [comment]
而且你的文件解压之后，打开之后乱码,是不是因为操作系统不一样呢？

**Comment by JYS997760473** [comment]
我的是mac系统 你可以再试一下这个url：https://github.com/xinshuoweng/Xinshuo_PyToolbox.git 在这里下一下这个包

**Comment by zuzi2015** [comment]
可以使用了，谢谢！

**Comment by zuzi2015** [comment]
请问你放在项目中的这个数据集是kitti数据集吗？看着不像啊，还是由kitti生成的label,你解释一下各个列代表什么吗？

**Comment by zuzi2015** [comment]
能不能发个你的数据集格式？谢谢

**Comment by JYS997760473** [comment]
刚刚上传了一个数据文件 0000.txt

**Comment by zuzi2015** [comment]
您好，我换了自己的数据集之后，跟踪结果只能出现前三帧，后面都没有跟踪结果，这可能是什么原因呢？
![image](https://user-images.githubusercontent.com/23184892/165244635-9a39f686-ae7a-4b5d-b1d2-61d15f99abd6.png)
这是我的数据集格式：
0,2,114,19,117,17
0,2,67,44,71,41
0,2,53,36,57,33
0,2,39,49,43,47
0,2,17,3,22,1
0,2,0,11,5,8
0,2,0,59,4,57
0,2,55,798,57,794

**Comment by JYS997760473** [comment]
这个好奇怪

**Comment by JYS997760473** [comment]
我目前就试了KITTI的数据集 其他的没有试过
